name: Update Chat README
on:
  issues:
    types: [opened, edited]

jobs:
  update-chat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyGithub
        run: pip install PyGithub

      - name: Update README
        run: python update_chat.py

      - name: Commit README
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "actions@github.com"
          git add README.md
          git commit -m "Update chat log" || echo "No changes to commit"
          git push
